version: '3.8'
services:
  api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1 